### DISCUSSION TITLE
[Question] Can we make a pagination in Horizontal Scroll Mode?

### DISCUSSION THREAD

**Discussion by catmans1** [mozilla/pdf.js#17774] [Q&A] [answered]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: `None`
- Operating system and its version: `Safari mobile`
- PDF.js version: `3.11.174`
- Is a browser extension: `None`

Steps to reproduce the problem: `None`
1. 
2.

What is the expected behavior? (add screenshot)

**`Can we make a pagination in Horizontal Scroll Mode?`**

I tried to add the class in `viewerContainer` element, but it didn't work

```css
.scroll-container {
  display: flex;
  overflow-x: scroll !important;
  scroll-snap-type: x mandatory;
  -webkit-scroll-snap-type: x mandatory;
  scrollbar-width: none;
  -ms-overflow-style: none;
  -webkit-overflow-scrolling: touch;
}

.scroll-container::-webkit-scrollbar {
  display: none;
}
```

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
