### ISSUE TITLE
Unable to remove toolbar and margins

### ISSUE THREAD

**Issue by JakeQZ** [mozilla/pdf.js#13153]
Attach (recommended) or Link to PDF file here: irrelevant

Configuration:
- Web browser and its version: all
- Operating system and its version: all
- PDF.js version: 2.6.347-es5
- Is a browser extension: no

Steps to reproduce the problem:
1. Embed PDF via `iframe` with `src=/web/viewer.html?file=some.pdf`
2. Hack the `viewer.css` to add the following (to try to remove the toolbar and margins):

```css
div.toolbar {
  display: none;
}
#viewerContainer {
  top: 0;
}
.pdfViewer .page {
  margin: 0;
  border: 0;
  padding: 0;
}
```

What is the expected behavior? (add screenshot)

PDF content fills container

What went wrong? (add screenshot)

PDF content has (grey) margins to the right and below (randomly either about 32px right and 24px below or 8px right and 6px below, for A4 landscape PDF)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): n/a

<strong>`width` and `height` style properties are being set on the `div.page`, `div.canvasWrapper` and `div.textLayer` elements, as well as as attributes on the `canvas`.

I just need to know where in the JavaScript these are being set, so I can investigate further.  I have been unable to find what part of the code is doing this - surely somebody must know.</strong>

**Comment by JakeQZ** [comment]
Solved it, I think.

It also needs

```css
#viewerContainer,
#viewer {
  overflow-y: hidden;
}
```

otherwise when it does the measuring there is (or might be) a scrollbar.

It also needs

```js
var SCROLLBAR_PADDING = 0;
var VERTICAL_PADDING = 0;
```

in `viewer.js` changing from the strange default values.
