### ISSUE TITLE
Please avoid causing periodic wakeups in Firefox

### ISSUE THREAD

**Issue by amonakov** [mozilla/pdf.js#14242]
Configuration:
- Web browser and its version: Firefox 94
- Operating system and its version: Linux
- PDF.js version: browser built-in

Steps to reproduce the problem:
1. Open any PDF in Firefox via pdf.js (either built-in or standalone)
2. Observe that as long as the tab with the PDF is open, the browser has increased CPU usage (visible in `top`) and is waking up rapidly (visible in `powertop`), probably updating the page for each vsync (GPU interrupts go up). Unfortunately, profiling via developer tools does not show anything.

What is the expected behavior? The tab with the PDF should not cause the browser to wake up when I do not interact with it.

What went wrong? The tab with the PDF is somehow causing periodic activity in the browser many times per second, causing unnecessary CPU usage and energy waste.

**Comment by jrmuizel** [comment]
Can you share a link to a profile created with https://profiler.firefox.com?

**Comment by amonakov** [comment]
Here you go: https://share.firefox.dev/3mYMSgf

As you can see in the "Marker Table" tab, there's RefreshDriverTick with `Tick reasons: HasImageAnimations` firing 60 times per second. The PDF I opened doesn't have any interactive elements (it's the online demo from the Github readme, https://mozilla.github.io/pdf.js/web/viewer.html), so there should be no reason to refresh it at 60 fps.

**Comment by jrmuizel** [comment]
It looks like this is caused by `loading-icon.gif` used from:
```css
.pdfViewer .page .loadingIcon {
  position: absolute;
  display: none;
  left: 0;
  top: 0;
  right: 0;
  bottom: 0;
  background: url("images/loading-icon.gif") center no-repeat;
}
```

We should probably set the throbber to display: none or something when we're not using it.
