### ISSUE TITLE
[Bug]: web viewer style for `[hidden]` not work correctly

### ISSUE THREAD

**Issue by zhaojjiang** [mozilla/pdf.js#18704]
### Attach (recommended) or Link to PDF file

any

### Web browser and its version

any

### Operating system and its version

any

### PDF.js version

4.6.82

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

when i add `[hidden]` to `web/viewer.html`, some button not hide correctly,

```html
<button id="secondaryPrint" class="toolbarButton labeled visibleMediumView" type="button" title="Print" tabindex="52" data-l10n-id="pdfjs-print-button" hidden>
  <span data-l10n-id="pdfjs-print-button-label">Print</span>
</button>

<button id="secondaryDownload" class="toolbarButton labeled visibleMediumView" type="button" title="Save" tabindex="53" data-l10n-id="pdfjs-save-button" hidden>
  <span data-l10n-id="pdfjs-save-button-label">Save</span>
</button>
```

style

```css
.hidden,
[hidden] {
  display: none !important;
}
```

overwrite by

```css
@media all and (max-width: 750px) {
  :root {
    --editor-toolbar-base-offset: 40px;
  }
  #outerContainer .hiddenMediumView {
    display: none !important;
  }
  #outerContainer .visibleMediumView {
    display: inherit !important;
  }
}
```

### What is the expected behavior?

`[hideden]` should have highest priority

### What went wrong?

`[hidden]` not work for some elements
